name: prod

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: install & test
      run: npm cit
    - name: serverless deploy
      uses: tegud/serverless-github-action@3fe770b519365a942eb4c38069726a833a0fb01f
      with:
        command: deploy
        args: "--stage=dev"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
